// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace Com.Resourcebox.Sbe
{
    /// <summary>
    /// 리스트 형태 메시지
    /// </summary>
    public sealed partial class ListStatusMessage
    {
        public const ushort BlockLength = (ushort)0;
        public const ushort TemplateId = (ushort)3;
        public const ushort SchemaId = (ushort)1;
        public const ushort SchemaVersion = (ushort)0;
        public const string SemanticType = "";
        public const string SemanticVersion = "1.0";

        private readonly ListStatusMessage _parentMessage;
        private DirectBuffer _buffer;
        private int _offset;
        private int _limit;
        private int _actingBlockLength;
        private int _actingVersion;

        public int Offset { get { return _offset; } }

        public ListStatusMessage()
        {
            _parentMessage = this;
        }

        public ListStatusMessage WrapForEncode(DirectBuffer buffer, int offset)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = BlockLength;
            _actingVersion = SchemaVersion;
            Limit = offset + _actingBlockLength;
            return this;
        }

        public ListStatusMessage WrapForEncodeAndApplyHeader(DirectBuffer buffer, int offset, MessageHeader headerEncoder)
        {
            headerEncoder.Wrap(buffer, offset, SchemaVersion);
            headerEncoder.BlockLength = BlockLength;
            headerEncoder.TemplateId = TemplateId;
            headerEncoder.SchemaId = SchemaId;
            headerEncoder.Version = SchemaVersion;
            
            return WrapForEncode(buffer, offset + MessageHeader.Size);
        }

        public ListStatusMessage WrapForDecode(DirectBuffer buffer, int offset, int actingBlockLength, int actingVersion)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = actingBlockLength;
            _actingVersion = actingVersion;
            Limit = offset + _actingBlockLength;
            return this;
        }

        public ListStatusMessage WrapForDecodeAndApplyHeader(DirectBuffer buffer, int offset, MessageHeader headerDecoder)
        {
            headerDecoder.Wrap(buffer, offset, SchemaVersion);
            
            return WrapForDecode(buffer, offset + MessageHeader.Size,  headerDecoder.BlockLength, headerDecoder.Version);
        }

        public int Size
        {
            get
            {
                return _limit - _offset;
            }
        }

        public int Limit
        {
            get
            {
                return _limit;
            }
            set
            {
                _buffer.CheckLimit(value);
                _limit = value;
            }
        }


        private readonly TimestampGroup _timestamp = new TimestampGroup();

        public const long TimestampId = 1;
        public const int TimestampSinceVersion = 0;
        public const int TimestampDeprecated = 0;
        public bool TimestampInActingVersion()
        {
            return _actingVersion >= TimestampSinceVersion;
        }

        public TimestampGroup Timestamp
        {
            get
            {
                _timestamp.WrapForDecode(_parentMessage, _buffer, _actingVersion);
                return _timestamp;
            }
        }

        public TimestampGroup TimestampCount(int count)
        {
            _timestamp.WrapForEncode(_parentMessage, _buffer, count);
            return _timestamp;
        }

        public sealed partial class TimestampGroup
        {
            private readonly GroupSizeEncoding _dimensions = new GroupSizeEncoding();
            private ListStatusMessage _parentMessage;
            private DirectBuffer _buffer;
            private int _blockLength;
            private int _actingVersion;
            private int _count;
            private int _index;
            private int _offset;

            internal void NotPresent()
            {
                _count = 0;
                _index = 0;
                _buffer = null;
                _offset = 0;
            }

            public void WrapForDecode(ListStatusMessage parentMessage, DirectBuffer buffer, int actingVersion)
            {
                _parentMessage = parentMessage;
                _buffer = buffer;
                _dimensions.Wrap(buffer, parentMessage.Limit, actingVersion);
                _parentMessage.Limit = parentMessage.Limit + SbeHeaderSize;
                _blockLength = _dimensions.BlockLength;
                _count = (int) _dimensions.NumInGroup;
                _actingVersion = actingVersion;
                _index = 0;
            }

            public void WrapForEncode(ListStatusMessage parentMessage, DirectBuffer buffer, int count)
            {
                if ((uint) count > 65534)
                {
                    ThrowHelper.ThrowCountOutOfRangeException(count);
                }

                _parentMessage = parentMessage;
                _buffer = buffer;
                _dimensions.Wrap(buffer, parentMessage.Limit, SchemaVersion);
                parentMessage.Limit = parentMessage.Limit + SbeHeaderSize;
                _dimensions.BlockLength = SbeBlockLength;
                _dimensions.NumInGroup = (ushort) count;
                _index = 0;
                _count = count;
                _blockLength = SbeBlockLength;
                _actingVersion = SchemaVersion;
            }

            public const int SbeBlockLength = 0;
            public const int SbeHeaderSize = 4;
            public int ActingBlockLength { get { return _blockLength; } }

            public int Count { get { return _count; } }

            public bool HasNext { get { return _index < _count; } }


            public int ResetCountToIndex()
            {
                _count = _index;
                _dimensions.NumInGroup = (ushort) _count;

                return _count;
            }

            public TimestampGroup Next()
            {
                if (_index >= _count)
                {
                    ThrowHelper.ThrowInvalidOperationException();
                }

                _offset = _parentMessage.Limit;
                _parentMessage.Limit = _offset + _blockLength;
                ++_index;

                return this;
            }

            public System.Collections.IEnumerator GetEnumerator()
            {
                while (this.HasNext)
                {
                    yield return this.Next();
                }
            }

            public const int ValueId = 1;
            public const int ValueSinceVersion = 0;
            public const int ValueDeprecated = 0;
            public bool ValueInActingVersion()
            {
                return _actingVersion >= ValueSinceVersion;
            }

            public const int ValueOffset = 0;

            public const string ValueCharacterEncoding = "UTF-8";
            public static Encoding ValueResolvedCharacterEncoding = Encoding.GetEncoding(ValueCharacterEncoding);


            public static string ValueMetaAttribute(MetaAttribute metaAttribute)
            {
                switch (metaAttribute)
                {
                    case MetaAttribute.Epoch: return "";
                    case MetaAttribute.TimeUnit: return "";
                    case MetaAttribute.SemanticType: return "";
                    case MetaAttribute.Presence: return "required";
                }

                return "";
            }

            public const int ValueHeaderSize = 4;
            
            public int ValueLength()
            {
                _buffer.CheckLimit(_parentMessage.Limit + 4);
                return (int)_buffer.Uint32GetLittleEndian(_parentMessage.Limit);
            }

            public int GetValue(byte[] dst, int dstOffset, int length) =>
                GetValue(new Span<byte>(dst, dstOffset, length));

            public int GetValue(Span<byte> dst)
            {
                const int sizeOfLengthField = 4;
                int limit = _parentMessage.Limit;
                _buffer.CheckLimit(limit + sizeOfLengthField);
                int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
                int bytesCopied = Math.Min(dst.Length, dataLength);
                _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
                _buffer.GetBytes(limit + sizeOfLengthField, dst.Slice(0, bytesCopied));

                return bytesCopied;
            }
            
            // Allocates and returns a new byte array
            public byte[] GetValueBytes()
            {
                const int sizeOfLengthField = 4;
                int limit = _parentMessage.Limit;
                _buffer.CheckLimit(limit + sizeOfLengthField);
                int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
                byte[] data = new byte[dataLength];
                _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
                _buffer.GetBytes(limit + sizeOfLengthField, data);

                return data;
            }

            public int SetValue(byte[] src, int srcOffset, int length) =>
                SetValue(new ReadOnlySpan<byte>(src, srcOffset, length));

            public int SetValue(ReadOnlySpan<byte> src)
            {
                const int sizeOfLengthField = 4;
                int limit = _parentMessage.Limit;
                _parentMessage.Limit = limit + sizeOfLengthField + src.Length;
                _buffer.Uint32PutLittleEndian(limit, (uint)src.Length);
                _buffer.SetBytes(limit + sizeOfLengthField, src);

                return src.Length;
            }

            public string GetValue()
            {
                const int sizeOfLengthField = 4;
                int limit = _parentMessage.Limit;
                _buffer.CheckLimit(limit + sizeOfLengthField);
                int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
                _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
                return _buffer.GetStringFromBytes(ValueResolvedCharacterEncoding, limit + sizeOfLengthField, dataLength);
            }

            public void SetValue(string value)
            {
                var encoding = ValueResolvedCharacterEncoding;
                const int sizeOfLengthField = 4;
                int limit = _parentMessage.Limit;
                int byteCount = _buffer.SetBytesFromString(encoding, value, limit + sizeOfLengthField);
                _parentMessage.Limit = limit + sizeOfLengthField + byteCount;
                _buffer.Uint32PutLittleEndian(limit, (uint)byteCount);
            }

                internal void BuildString(StringBuilder builder)
                {
                    if (_buffer == null)
                    {
                        return;
                    }

                    builder.Append('(');
                    builder.Append("Value=");
                    builder.Append('\'').Append(GetValue()).Append('\'');
                    builder.Append(')');

                }
        }

        private readonly EntriesGroup _entries = new EntriesGroup();

        public const long EntriesId = 2;
        public const int EntriesSinceVersion = 0;
        public const int EntriesDeprecated = 0;
        public bool EntriesInActingVersion()
        {
            return _actingVersion >= EntriesSinceVersion;
        }

        public EntriesGroup Entries
        {
            get
            {
                _entries.WrapForDecode(_parentMessage, _buffer, _actingVersion);
                return _entries;
            }
        }

        public EntriesGroup EntriesCount(int count)
        {
            _entries.WrapForEncode(_parentMessage, _buffer, count);
            return _entries;
        }

        public sealed partial class EntriesGroup
        {
            private readonly GroupSizeEncoding _dimensions = new GroupSizeEncoding();
            private ListStatusMessage _parentMessage;
            private DirectBuffer _buffer;
            private int _blockLength;
            private int _actingVersion;
            private int _count;
            private int _index;
            private int _offset;

            internal void NotPresent()
            {
                _count = 0;
                _index = 0;
                _buffer = null;
                _offset = 0;
            }

            public void WrapForDecode(ListStatusMessage parentMessage, DirectBuffer buffer, int actingVersion)
            {
                _parentMessage = parentMessage;
                _buffer = buffer;
                _dimensions.Wrap(buffer, parentMessage.Limit, actingVersion);
                _parentMessage.Limit = parentMessage.Limit + SbeHeaderSize;
                _blockLength = _dimensions.BlockLength;
                _count = (int) _dimensions.NumInGroup;
                _actingVersion = actingVersion;
                _index = 0;
            }

            public void WrapForEncode(ListStatusMessage parentMessage, DirectBuffer buffer, int count)
            {
                if ((uint) count > 65534)
                {
                    ThrowHelper.ThrowCountOutOfRangeException(count);
                }

                _parentMessage = parentMessage;
                _buffer = buffer;
                _dimensions.Wrap(buffer, parentMessage.Limit, SchemaVersion);
                parentMessage.Limit = parentMessage.Limit + SbeHeaderSize;
                _dimensions.BlockLength = SbeBlockLength;
                _dimensions.NumInGroup = (ushort) count;
                _index = 0;
                _count = count;
                _blockLength = SbeBlockLength;
                _actingVersion = SchemaVersion;
            }

            public const int SbeBlockLength = 4;
            public const int SbeHeaderSize = 4;
            public int ActingBlockLength { get { return _blockLength; } }

            public int Count { get { return _count; } }

            public bool HasNext { get { return _index < _count; } }


            public int ResetCountToIndex()
            {
                _count = _index;
                _dimensions.NumInGroup = (ushort) _count;

                return _count;
            }

            public EntriesGroup Next()
            {
                if (_index >= _count)
                {
                    ThrowHelper.ThrowInvalidOperationException();
                }

                _offset = _parentMessage.Limit;
                _parentMessage.Limit = _offset + _blockLength;
                ++_index;

                return this;
            }

            public System.Collections.IEnumerator GetEnumerator()
            {
                while (this.HasNext)
                {
                    yield return this.Next();
                }
            }

            public const int IdId = 1;
            public const int IdSinceVersion = 0;
            public const int IdDeprecated = 0;
            public bool IdInActingVersion()
            {
                return _actingVersion >= IdSinceVersion;
            }

            public const int IdOffset = 0;

            public static string IdMetaAttribute(MetaAttribute metaAttribute)
            {
                switch (metaAttribute)
                {
                    case MetaAttribute.Epoch: return "";
                    case MetaAttribute.TimeUnit: return "";
                    case MetaAttribute.SemanticType: return "";
                    case MetaAttribute.Presence: return "required";
                }

                return "";
            }

            public const int IdNullValue = -2147483648;
            public const int IdMinValue = -2147483647;
            public const int IdMaxValue = 2147483647;

            public int Id
            {
                get
                {
                    return _buffer.Int32GetLittleEndian(_offset + 0);
                }
                set
                {
                    _buffer.Int32PutLittleEndian(_offset + 0, value);
                }
            }


            public const int ValueId = 2;
            public const int ValueSinceVersion = 0;
            public const int ValueDeprecated = 0;
            public bool ValueInActingVersion()
            {
                return _actingVersion >= ValueSinceVersion;
            }

            public const int ValueOffset = 4;

            public const string ValueCharacterEncoding = "UTF-8";
            public static Encoding ValueResolvedCharacterEncoding = Encoding.GetEncoding(ValueCharacterEncoding);


            public static string ValueMetaAttribute(MetaAttribute metaAttribute)
            {
                switch (metaAttribute)
                {
                    case MetaAttribute.Epoch: return "";
                    case MetaAttribute.TimeUnit: return "";
                    case MetaAttribute.SemanticType: return "";
                    case MetaAttribute.Presence: return "required";
                }

                return "";
            }

            public const int ValueHeaderSize = 4;
            
            public int ValueLength()
            {
                _buffer.CheckLimit(_parentMessage.Limit + 4);
                return (int)_buffer.Uint32GetLittleEndian(_parentMessage.Limit);
            }

            public int GetValue(byte[] dst, int dstOffset, int length) =>
                GetValue(new Span<byte>(dst, dstOffset, length));

            public int GetValue(Span<byte> dst)
            {
                const int sizeOfLengthField = 4;
                int limit = _parentMessage.Limit;
                _buffer.CheckLimit(limit + sizeOfLengthField);
                int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
                int bytesCopied = Math.Min(dst.Length, dataLength);
                _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
                _buffer.GetBytes(limit + sizeOfLengthField, dst.Slice(0, bytesCopied));

                return bytesCopied;
            }
            
            // Allocates and returns a new byte array
            public byte[] GetValueBytes()
            {
                const int sizeOfLengthField = 4;
                int limit = _parentMessage.Limit;
                _buffer.CheckLimit(limit + sizeOfLengthField);
                int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
                byte[] data = new byte[dataLength];
                _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
                _buffer.GetBytes(limit + sizeOfLengthField, data);

                return data;
            }

            public int SetValue(byte[] src, int srcOffset, int length) =>
                SetValue(new ReadOnlySpan<byte>(src, srcOffset, length));

            public int SetValue(ReadOnlySpan<byte> src)
            {
                const int sizeOfLengthField = 4;
                int limit = _parentMessage.Limit;
                _parentMessage.Limit = limit + sizeOfLengthField + src.Length;
                _buffer.Uint32PutLittleEndian(limit, (uint)src.Length);
                _buffer.SetBytes(limit + sizeOfLengthField, src);

                return src.Length;
            }

            public string GetValue()
            {
                const int sizeOfLengthField = 4;
                int limit = _parentMessage.Limit;
                _buffer.CheckLimit(limit + sizeOfLengthField);
                int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
                _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
                return _buffer.GetStringFromBytes(ValueResolvedCharacterEncoding, limit + sizeOfLengthField, dataLength);
            }

            public void SetValue(string value)
            {
                var encoding = ValueResolvedCharacterEncoding;
                const int sizeOfLengthField = 4;
                int limit = _parentMessage.Limit;
                int byteCount = _buffer.SetBytesFromString(encoding, value, limit + sizeOfLengthField);
                _parentMessage.Limit = limit + sizeOfLengthField + byteCount;
                _buffer.Uint32PutLittleEndian(limit, (uint)byteCount);
            }

                internal void BuildString(StringBuilder builder)
                {
                    if (_buffer == null)
                    {
                        return;
                    }

                    builder.Append('(');
                    builder.Append("Id=");
                    builder.Append(this.Id);
                    builder.Append('|');
                    builder.Append("Value=");
                    builder.Append('\'').Append(GetValue()).Append('\'');
                    builder.Append(')');

                }
        }

        public override string ToString()
        {
            var sb = new StringBuilder(100);
            var m = new ListStatusMessage();
            m.WrapForDecode(_buffer, _offset, _actingBlockLength, _actingVersion);
            m.BuildString(sb);
            return sb.ToString();
        }

        internal void BuildString(StringBuilder builder)
        {
            if (_buffer == null)
            {
                throw new ArgumentNullException("_buffer");
            }

            int originalLimit = this.Limit;
            this.Limit = _offset + _actingBlockLength;
            builder.Append("[ListStatusMessage](sbeTemplateId=");
            builder.Append(ListStatusMessage.TemplateId);
            builder.Append("|sbeSchemaId=");
            builder.Append(ListStatusMessage.SchemaId);
            builder.Append("|sbeSchemaVersion=");
            if (_parentMessage._actingVersion != ListStatusMessage.SchemaVersion)
            {
                builder.Append(_parentMessage._actingVersion);
                builder.Append('/');
            }
            builder.Append(ListStatusMessage.SchemaVersion);
            builder.Append("|sbeBlockLength=");
            if (_actingBlockLength != ListStatusMessage.BlockLength)
            {
                builder.Append(_actingBlockLength);
                builder.Append('/');
            }
            builder.Append(ListStatusMessage.BlockLength);
            builder.Append("):");

            builder.Append("Timestamp=[");
            var timestamp = this.Timestamp;
            if (timestamp.Count > 0)
            {
                var first = true;
                while (timestamp.HasNext)
                {
                    if (!first)
                    {
                        builder.Append(',');
                    }
                    first = false;
                    timestamp.Next().BuildString(builder);
                }
            }
            builder.Append("]");
            builder.Append('|');
            builder.Append("Entries=[");
            var entries = this.Entries;
            if (entries.Count > 0)
            {
                var first = true;
                while (entries.HasNext)
                {
                    if (!first)
                    {
                        builder.Append(',');
                    }
                    first = false;
                    entries.Next().BuildString(builder);
                }
            }
            builder.Append("]");

            this.Limit = originalLimit;

        }
    }
}
