// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace Com.Resourcebox.Sbe
{
    /// <summary>
    /// 단일 속성값 메시지
    /// </summary>
    public sealed partial class SingleDataMessage
    {
        public const ushort BlockLength = (ushort)4;
        public const ushort TemplateId = (ushort)1;
        public const ushort SchemaId = (ushort)1;
        public const ushort SchemaVersion = (ushort)0;
        public const string SemanticType = "";
        public const string SemanticVersion = "1.0";

        private readonly SingleDataMessage _parentMessage;
        private DirectBuffer _buffer;
        private int _offset;
        private int _limit;
        private int _actingBlockLength;
        private int _actingVersion;

        public int Offset { get { return _offset; } }

        public SingleDataMessage()
        {
            _parentMessage = this;
        }

        public SingleDataMessage WrapForEncode(DirectBuffer buffer, int offset)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = BlockLength;
            _actingVersion = SchemaVersion;
            Limit = offset + _actingBlockLength;
            return this;
        }

        public SingleDataMessage WrapForEncodeAndApplyHeader(DirectBuffer buffer, int offset, MessageHeader headerEncoder)
        {
            headerEncoder.Wrap(buffer, offset, SchemaVersion);
            headerEncoder.BlockLength = BlockLength;
            headerEncoder.TemplateId = TemplateId;
            headerEncoder.SchemaId = SchemaId;
            headerEncoder.Version = SchemaVersion;
            
            return WrapForEncode(buffer, offset + MessageHeader.Size);
        }

        public SingleDataMessage WrapForDecode(DirectBuffer buffer, int offset, int actingBlockLength, int actingVersion)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = actingBlockLength;
            _actingVersion = actingVersion;
            Limit = offset + _actingBlockLength;
            return this;
        }

        public SingleDataMessage WrapForDecodeAndApplyHeader(DirectBuffer buffer, int offset, MessageHeader headerDecoder)
        {
            headerDecoder.Wrap(buffer, offset, SchemaVersion);
            
            return WrapForDecode(buffer, offset + MessageHeader.Size,  headerDecoder.BlockLength, headerDecoder.Version);
        }

        public int Size
        {
            get
            {
                return _limit - _offset;
            }
        }

        public int Limit
        {
            get
            {
                return _limit;
            }
            set
            {
                _buffer.CheckLimit(value);
                _limit = value;
            }
        }


        public const int IdId = 1;
        public const int IdSinceVersion = 0;
        public const int IdDeprecated = 0;
        public bool IdInActingVersion()
        {
            return _actingVersion >= IdSinceVersion;
        }

        public const int IdOffset = 0;

        public static string IdMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const int IdNullValue = -2147483648;
        public const int IdMinValue = -2147483647;
        public const int IdMaxValue = 2147483647;

        public int Id
        {
            get
            {
                return _buffer.Int32GetLittleEndian(_offset + 0);
            }
            set
            {
                _buffer.Int32PutLittleEndian(_offset + 0, value);
            }
        }


        public const int ValueId = 2;
        public const int ValueSinceVersion = 0;
        public const int ValueDeprecated = 0;
        public bool ValueInActingVersion()
        {
            return _actingVersion >= ValueSinceVersion;
        }

        public const int ValueOffset = 4;

        public const string ValueCharacterEncoding = "UTF-8";
        public static Encoding ValueResolvedCharacterEncoding = Encoding.GetEncoding(ValueCharacterEncoding);


        public static string ValueMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const int ValueHeaderSize = 4;
        
        public int ValueLength()
        {
            _buffer.CheckLimit(_parentMessage.Limit + 4);
            return (int)_buffer.Uint32GetLittleEndian(_parentMessage.Limit);
        }

        public int GetValue(byte[] dst, int dstOffset, int length) =>
            GetValue(new Span<byte>(dst, dstOffset, length));

        public int GetValue(Span<byte> dst)
        {
            const int sizeOfLengthField = 4;
            int limit = _parentMessage.Limit;
            _buffer.CheckLimit(limit + sizeOfLengthField);
            int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
            int bytesCopied = Math.Min(dst.Length, dataLength);
            _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
            _buffer.GetBytes(limit + sizeOfLengthField, dst.Slice(0, bytesCopied));

            return bytesCopied;
        }
        
        // Allocates and returns a new byte array
        public byte[] GetValueBytes()
        {
            const int sizeOfLengthField = 4;
            int limit = _parentMessage.Limit;
            _buffer.CheckLimit(limit + sizeOfLengthField);
            int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
            byte[] data = new byte[dataLength];
            _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
            _buffer.GetBytes(limit + sizeOfLengthField, data);

            return data;
        }

        public int SetValue(byte[] src, int srcOffset, int length) =>
            SetValue(new ReadOnlySpan<byte>(src, srcOffset, length));

        public int SetValue(ReadOnlySpan<byte> src)
        {
            const int sizeOfLengthField = 4;
            int limit = _parentMessage.Limit;
            _parentMessage.Limit = limit + sizeOfLengthField + src.Length;
            _buffer.Uint32PutLittleEndian(limit, (uint)src.Length);
            _buffer.SetBytes(limit + sizeOfLengthField, src);

            return src.Length;
        }

        public string GetValue()
        {
            const int sizeOfLengthField = 4;
            int limit = _parentMessage.Limit;
            _buffer.CheckLimit(limit + sizeOfLengthField);
            int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
            _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
            return _buffer.GetStringFromBytes(ValueResolvedCharacterEncoding, limit + sizeOfLengthField, dataLength);
        }

        public void SetValue(string value)
        {
            var encoding = ValueResolvedCharacterEncoding;
            const int sizeOfLengthField = 4;
            int limit = _parentMessage.Limit;
            int byteCount = _buffer.SetBytesFromString(encoding, value, limit + sizeOfLengthField);
            _parentMessage.Limit = limit + sizeOfLengthField + byteCount;
            _buffer.Uint32PutLittleEndian(limit, (uint)byteCount);
        }

        public const int TimestampId = 3;
        public const int TimestampSinceVersion = 0;
        public const int TimestampDeprecated = 0;
        public bool TimestampInActingVersion()
        {
            return _actingVersion >= TimestampSinceVersion;
        }

        public const int TimestampOffset = -1;

        public const string TimestampCharacterEncoding = "UTF-8";
        public static Encoding TimestampResolvedCharacterEncoding = Encoding.GetEncoding(TimestampCharacterEncoding);


        public static string TimestampMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const int TimestampHeaderSize = 4;
        
        public int TimestampLength()
        {
            _buffer.CheckLimit(_parentMessage.Limit + 4);
            return (int)_buffer.Uint32GetLittleEndian(_parentMessage.Limit);
        }

        public int GetTimestamp(byte[] dst, int dstOffset, int length) =>
            GetTimestamp(new Span<byte>(dst, dstOffset, length));

        public int GetTimestamp(Span<byte> dst)
        {
            const int sizeOfLengthField = 4;
            int limit = _parentMessage.Limit;
            _buffer.CheckLimit(limit + sizeOfLengthField);
            int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
            int bytesCopied = Math.Min(dst.Length, dataLength);
            _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
            _buffer.GetBytes(limit + sizeOfLengthField, dst.Slice(0, bytesCopied));

            return bytesCopied;
        }
        
        // Allocates and returns a new byte array
        public byte[] GetTimestampBytes()
        {
            const int sizeOfLengthField = 4;
            int limit = _parentMessage.Limit;
            _buffer.CheckLimit(limit + sizeOfLengthField);
            int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
            byte[] data = new byte[dataLength];
            _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
            _buffer.GetBytes(limit + sizeOfLengthField, data);

            return data;
        }

        public int SetTimestamp(byte[] src, int srcOffset, int length) =>
            SetTimestamp(new ReadOnlySpan<byte>(src, srcOffset, length));

        public int SetTimestamp(ReadOnlySpan<byte> src)
        {
            const int sizeOfLengthField = 4;
            int limit = _parentMessage.Limit;
            _parentMessage.Limit = limit + sizeOfLengthField + src.Length;
            _buffer.Uint32PutLittleEndian(limit, (uint)src.Length);
            _buffer.SetBytes(limit + sizeOfLengthField, src);

            return src.Length;
        }

        public string GetTimestamp()
        {
            const int sizeOfLengthField = 4;
            int limit = _parentMessage.Limit;
            _buffer.CheckLimit(limit + sizeOfLengthField);
            int dataLength = (int)_buffer.Uint32GetLittleEndian(limit);
            _parentMessage.Limit = limit + sizeOfLengthField + dataLength;
            return _buffer.GetStringFromBytes(TimestampResolvedCharacterEncoding, limit + sizeOfLengthField, dataLength);
        }

        public void SetTimestamp(string value)
        {
            var encoding = TimestampResolvedCharacterEncoding;
            const int sizeOfLengthField = 4;
            int limit = _parentMessage.Limit;
            int byteCount = _buffer.SetBytesFromString(encoding, value, limit + sizeOfLengthField);
            _parentMessage.Limit = limit + sizeOfLengthField + byteCount;
            _buffer.Uint32PutLittleEndian(limit, (uint)byteCount);
        }

        public override string ToString()
        {
            var sb = new StringBuilder(100);
            var m = new SingleDataMessage();
            m.WrapForDecode(_buffer, _offset, _actingBlockLength, _actingVersion);
            m.BuildString(sb);
            return sb.ToString();
        }

        internal void BuildString(StringBuilder builder)
        {
            if (_buffer == null)
            {
                throw new ArgumentNullException("_buffer");
            }

            int originalLimit = this.Limit;
            this.Limit = _offset + _actingBlockLength;
            builder.Append("[SingleDataMessage](sbeTemplateId=");
            builder.Append(SingleDataMessage.TemplateId);
            builder.Append("|sbeSchemaId=");
            builder.Append(SingleDataMessage.SchemaId);
            builder.Append("|sbeSchemaVersion=");
            if (_parentMessage._actingVersion != SingleDataMessage.SchemaVersion)
            {
                builder.Append(_parentMessage._actingVersion);
                builder.Append('/');
            }
            builder.Append(SingleDataMessage.SchemaVersion);
            builder.Append("|sbeBlockLength=");
            if (_actingBlockLength != SingleDataMessage.BlockLength)
            {
                builder.Append(_actingBlockLength);
                builder.Append('/');
            }
            builder.Append(SingleDataMessage.BlockLength);
            builder.Append("):");

            builder.Append("Id=");
            builder.Append(this.Id);
            builder.Append('|');
            builder.Append("Value=");
            builder.Append('\'').Append(GetValue()).Append('\'');
            builder.Append('|');
            builder.Append("Timestamp=");
            builder.Append('\'').Append(GetTimestamp()).Append('\'');

            this.Limit = originalLimit;

        }
    }
}
